spring:
  batch:
    job:
      names: ${job.name:helloWorldJob}
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/SpringBatch_10?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true